### ISSUE TITLE
exception in GET - python branch

### ISSUE THREAD

**Issue by naveenkcb** [aws-samples/aws-modern-application-workshop#161]
Hi,
I completed till module 5 of the workshop but my website doesn't stay good for longtime.
Very few seconds I see all of the mysfits from the dynamoDB table where I can even select and mark as favourite but most of the time the "View All Mysfits" call results in failure..line no: 547 in index.html..

...This is my fist project on AWS and even building a web app for first time....if anyone can suggest a way to fix this, that would be great help

I have pasted the log below.

* Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
[2020-02-14 20:35:18,610] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "mythicalMysfitsService.py", line 12, in healthCheckResponse
    return jsonify(
{
    "message": "Nothing here, used for health check. Try /mysfits instead."
}
)
  File "/usr/local/lib/python2.7/dist-packages/flask/json.py", line 251, in jsonify
    if current_app.config['JSONIFY_PRETTYPRINT_REGULAR'] and not request.is_xhr:
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'is_xhr'
10.0.0.10 - - [14/Feb/2020 20:35:18] "[35m[1mGET / HTTP/1.1[0m" 500 -
[2020-02-14 20:35:18,640] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request

**Comment by joblini** [comment]
The problem is due to a breaking change in version 1.0 of the Werkzeug library, as described here:
https://stackoverflow.com/questions/60131900/weird-is-xhr-error-when-deploying-flask-app-to-heroku

I was able to work around the issue by adding the following to the requirements.txt file in the project:

**werkzeug<1.0**

**Comment by eduever** [comment]
> The problem is due to a breaking change in version 1.0 of the Werkzeug library, as described here:
> https://stackoverflow.com/questions/60131900/weird-is-xhr-error-when-deploying-flask-app-to-heroku
> 
> I was able to work around the issue by adding the following to the requirements.txt file in the project:
> 
> **werkzeug<1.0**

Thank you, i had same issue now its working. @joblini
