### ISSUE TITLE
Preview Running Application problem 

### ISSUE THREAD

**Issue by lesliewubbel** [aws-samples/aws-modern-application-workshop#167]
I am following the build docker image and in section 'B: Test The Service Locally' 

I run the command docker run -p 8080:8080 REPLACE_ME_WITH_DOCKER_IMAGE_TAG 

with the tag and its results in 
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)

right well when I preview the application I get this error.

[2020-03-17 18:16:56,604] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "mythicalMysfitsService.py", line 13, in healthCheckResponse
    return jsonify({"message" : "Nothing here, used for health check. Try /mysfits instead."})
  File "/usr/local/lib/python2.7/dist-packages/flask/json.py", line 251, in jsonify
    if current_app.config['JSONIFY_PRETTYPRINT_REGULAR'] and not request.is_xhr:
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'is_xhr'
172.17.0.1 - - [17/Mar/2020 18:16:56] "GET / HTTP/1.1" 500 -

is this normal?

**Comment by lesliewubbel** [comment]
Apparently its fixable with the addition of werkzeug<1.0  or werkzeug == 0.16.1
to the requirements.txt file 

I read ran the 

docker .build 

docker run 

and it works! 
{
  "message": "Nothing here, used for health check. Try /mysfits instead."
}

please add werkzeug<1.0 to make it work
