### ISSUE TITLE
mysfitsTableClient.py error at deployment post build

### ISSUE THREAD

**Issue by AndrewMcFarren** [aws-samples/aws-modern-application-workshop#200]
Hi All,

I actually deployed this in EKS as a K8s deployment and still going through the steps to build the container image.  However, when I deploy to EKS, in the past (Feb '20) this worked.  I updated pip version and Dockerfile to work with latest Ubuntu image (FROM ubuntu latest), but I still get this error in python code.  Please help fix.  Love the workshop!

~/environment/service $ kubectl logs -n mythical-mysfits  mythical-deployment-bf896b8f9-ckczj 
Traceback (most recent call last):
  File "mythicalMysfitsService.py", line 3, in <module>
    import mysfitsTableClient
  File "/MythicalMysfitsService/mysfitsTableClient.py", line 104
    print 'filter is '+args.filter
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('filter is '+args.filter)?

**Comment by AndrewMcFarren** [comment]
Docker build works fine, but the deployment in EKS from the image does not work.

**Comment by jayachandranm** [comment]
This issue is likely caused by Python2.7 / Python-3 print function difference. With Python-3, try modifying the code to use,
> print('filter is '+args.filter)

instead of,
> print 'filter is '+args.filter

And for all other prints.

**Comment by Codeama** [comment]
> This issue is likely caused by Python2.7 / Python-3 print function difference. With Python-3, try modifying the code to use,
> 
> > print('filter is '+args.filter)
> 
> instead of,
> 
> > print 'filter is '+args.filter
> 
> And for all other prints.

This helped me debug my issues. Thanks @jayachandranm
